// [目的] 開発用のモック店舗データ（将来的にFirestoreに移行）
import { Shop } from './Types';

export const MOCK_SHOPS: Shop[] = [
  {
    id: '1',
    name: 'Chop Hits Barbecue',
    area: 'other',
    genre: 'yakiniku',
    budgetMin: 3000,
    budgetMax: 5000,
    comment: 'BBQが楽しめるお店。',
    rating: 4.7,
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Chop+Hits+Barbecue',
    isActive: true,
    createdAt: '2026-03-31',
  },
  {
    id: '2',
    name: '川越',
    area: 'other',
    genre: 'izakaya',
    budgetMin: 2000,
    budgetMax: 4000,
    comment: '西区の穴場的なお店。',
    rating: 4.3,
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=川越+大阪市西区',
    isActive: true,
    createdAt: '2026-03-31',
  },
  {
    id: '3',
    name: '備長炉端だいやめ 京橋店',
    area: 'kyobashi',
    genre: 'izakaya',
    budgetMin: 3000,
    budgetMax: 4000,
    comment: '京橋で本格炉端焼きを楽しむならここ！',
    rating: 5.0,
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=備長炉端だいやめ+京橋店',
    isActive: true,
    createdAt: '2026-03-31',
  },
  {
    id: '4',
    name: '大阪ドカ盛りマンモス弁当 淡路総本店',
    area: 'other',
    genre: 'other',
    budgetMin: 500,
    budgetMax: 1000,
    comment: '圧倒的なボリュームのドカ盛り弁当！',
    rating: 3.9,
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=大阪ドカ盛りマンモス弁当+淡路総本店',
    isActive: true,
    createdAt: '2026-03-31',
  },
  {
    id: '5',
    name: 'いづう',
    area: 'other',
    genre: 'sushi',
    budgetMin: 2000,
    budgetMax: 4000,
    comment: '京都の伝統的な鯖姿寿司の名店。',
    rating: 4.2,
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=いづう+京都',
    isActive: true,
    createdAt: '2026-03-31',
  },
  {
    id: '6',
    name: '寿司処 眞',
    area: 'other',
    genre: 'sushi',
    budgetMin: 3000,
    budgetMax: 5000,
    comment: '落ち着いた雰囲気で美味しいお寿司を堪能。',
    rating: 4.3,
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=寿司処+眞',
    isActive: true,
    createdAt: '2026-03-31',
  },
  {
    id: '7',
    name: 'イタリア食堂 Necco',
    area: 'other',
    genre: 'other',
    budgetMin: 3000,
    budgetMax: 5000,
    comment: 'おしゃれでカジュアルなイタリアン食堂。',
    rating: 4.5,
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=イタリア食堂+Necco',
    isActive: true,
    createdAt: '2026-03-31',
  },
  {
    id: '8',
    name: '海坊主',
    area: 'other',
    genre: 'izakaya',
    budgetMin: 2000,
    budgetMax: 4000,
    comment: '淡路市の海鮮居酒屋！',
    rating: 4.2,
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=海坊主+淡路市',
    isActive: true,
    createdAt: '2026-03-31',
  },
  {
    id: '9',
    name: '洋風惣菜 アバ(コロッケ)',
    area: 'other',
    genre: 'other',
    budgetMin: 500,
    budgetMax: 1000,
    comment: '絶品のコロッケが名物！おやつにも最適。',
    rating: 4.4,
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=洋風惣菜+アバ',
    isActive: true,
    createdAt: '2026-03-31',
  },
  {
    id: '10',
    name: 'ラーメン ギタギタ',
    area: 'other',
    genre: 'ramen',
    budgetMin: 800,
    budgetMax: 1500,
    comment: '背脂たっぷりの濃厚ラーメン好きにはたまらない一杯。',
    rating: 4.0,
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=ラーメン+ギタギタ',
    isActive: true,
    createdAt: '2026-03-31',
  },
  {
    id: '11',
    name: 'ベンジャミーナ',
    area: 'other',
    genre: 'bar',
    budgetMin: 2000,
    budgetMax: 4000,
    comment: '雰囲気抜群のおしゃれなバー。',
    rating: 4.1,
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=ベンジャミーナ+大阪',
    isActive: true,
    createdAt: '2026-03-31',
  },
  {
    id: '12',
    name: '高知から来た焼肉屋',
    area: 'other',
    genre: 'yakiniku',
    budgetMin: 3000,
    budgetMax: 5000,
    comment: '高知流のこだわり焼肉を楽しめるお店。',
    rating: 4.2,
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=高知から来た焼肉屋',
    isActive: true,
    createdAt: '2026-03-31',
  },
  {
    id: '13',
    name: 'イノベーティブフレンチ genso',
    area: 'other',
    genre: 'other',
    budgetMin: 8000,
    budgetMax: 15000,
    comment: '究極のフレンチ体験ができる名店！',
    rating: 4.9,
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=イノベーティブフレンチ+genso',
    isActive: true,
    createdAt: '2026-03-31',
  },
  {
    id: '14',
    name: '豆ふと鮨と和食 ひとひ',
    area: 'other',
    genre: 'sushi',
    budgetMin: 4000,
    budgetMax: 6000,
    comment: '極上の豆腐とお鮨のハーモニー。',
    rating: 5.0,
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=豆ふと鮨と和食+ひとひ',
    isActive: true,
    createdAt: '2026-03-31',
  },
  {
    id: '15',
    name: 'うどん屋 きすけ',
    area: 'other',
    genre: 'other',
    budgetMin: 800,
    budgetMax: 1500,
    comment: '並んでも食べたい絶品うどん！',
    rating: 4.3,
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=うどん屋+きすけ',
    isActive: true,
    createdAt: '2026-03-31',
  },
  {
    id: '16',
    name: 'うどん 兎麦 umugi',
    area: 'umeda',
    genre: 'other',
    budgetMin: 800,
    budgetMax: 1500,
    comment: '行列ができる人気のうどん店。',
    rating: 4.2,
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=うどん+兎麦+umugi',
    isActive: true,
    createdAt: '2026-03-31',
  },
  {
    id: '17',
    name: '折鶴会館',
    area: 'other',
    genre: 'tachinomi',
    budgetMin: 1500,
    budgetMax: 3000,
    comment: '京都のディープな立ち飲みスポット。',
    rating: 4.5,
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=折鶴会館+京都',
    isActive: true,
    createdAt: '2026-03-31',
  },
  {
    id: '18',
    name: '鮨 暁',
    area: 'other',
    genre: 'sushi',
    budgetMin: 5000,
    budgetMax: 8000,
    comment: 'こだわりの握りを堪能できるお寿司屋さん。',
    rating: 4.6,
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=鮨+暁+大阪',
    isActive: true,
    createdAt: '2026-03-31',
  },
  {
    id: '19',
    name: '中華菜館 一番',
    area: 'other',
    genre: 'ramen',
    budgetMin: 1000,
    budgetMax: 2000,
    comment: '王道の町中華！',
    rating: 3.8,
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=中華菜館+一番+大阪',
    isActive: true,
    createdAt: '2026-03-31',
  },
  {
    id: '20',
    name: '特製ラーメン とん吉',
    area: 'other',
    genre: 'ramen',
    budgetMin: 800,
    budgetMax: 1200,
    comment: '昔ながらのホッとするラーメン。',
    rating: 4.1,
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=特製ラーメン+とん吉',
    isActive: true,
    createdAt: '2026-03-31',
  },
  {
    id: '21',
    name: '炭焼きイタリアン Black',
    area: 'other',
    genre: 'bar',
    budgetMin: 3000,
    budgetMax: 5000,
    comment: '炭焼き香るおしゃれなイタリアン。',
    rating: 4.7,
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=炭焼きイタリアン+Black',
    isActive: true,
    createdAt: '2026-03-31',
  },
  {
    id: '22',
    name: 'ラーメン食堂 神豚 大東店',
    area: 'other',
    genre: 'ramen',
    budgetMin: 800,
    budgetMax: 1200,
    comment: 'ガッツリいきたい時はここ！二郎系ラーメン。',
    rating: 3.5,
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=ラーメン食堂+神豚+大東店',
    isActive: true,
    createdAt: '2026-03-31',
  },
  {
    id: '23',
    name: '立ち呑み とおる',
    area: 'other',
    genre: 'tachinomi',
    budgetMin: 1500,
    budgetMax: 2500,
    comment: '一人でもフラリと入りやすい大衆立ち飲み！',
    rating: 4.5,
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=立ち呑み+とおる',
    isActive: true,
    createdAt: '2026-03-31',
  },
  {
    id: '24',
    name: '北新地 アンシェーヌ',
    area: 'umeda',
    genre: 'other',
    budgetMin: 8000,
    budgetMax: 15000,
    comment: '北新地で上質な時間とステーキを。',
    rating: 4.8,
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=北新地+アンシェーヌ',
    isActive: true,
    createdAt: '2026-03-31',
  },
  {
    id: '25',
    name: 'ロウリーズ・ザ・プライムリブ 大阪',
    area: 'umeda',
    genre: 'other',
    budgetMin: 10000,
    budgetMax: 20000,
    comment: '特別な日に最適！極上のプライムリブを満喫。',
    rating: 4.4,
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=ロウリーズ・ザ・プライムリブ+大阪',
    isActive: true,
    createdAt: '2026-03-31',
  }
];
