// [目的] 開発用のモック店舗データ（将来的にFirestoreに移行）
import { Shop } from './Types';

export const MOCK_SHOPS: Shop[] = [
  {
    id: '1',
    name: '立ち呑み あずき色のマーカス',
    area: 'tenma',
    genre: 'tachinomi',
    budgetMin: 2000,
    budgetMax: 3000,
    comment: '天満で迷ったらここ！立ち飲みとは思えないクオリティの料理。円形カウンターがおしゃれ。',
    rating: 5,
    googleMapsUrl: 'https://maps.google.com/?q=立ち呑みあずき色のマーカス+天満',
    isActive: true,
    createdAt: '2026-03-16',
  },
  {
    id: '2',
    name: 'stand dayoff',
    area: 'kitahama',
    genre: 'bar',
    budgetMin: 2500,
    budgetMax: 4000,
    comment: '北浜の隠れ家。無機質でおしゃれな内装と、ひねりの効いたドリンクメニューが最高。',
    rating: 4,
    googleMapsUrl: 'https://maps.google.com/?q=stand+dayoff+北浜',
    isActive: true,
    createdAt: '2026-03-16',
  },
  {
    id: '3',
    name: '大衆とり酒場 とりいちず 鶴橋店',
    area: 'tsuruhashi',
    genre: 'yakitori',
    budgetMin: 1500,
    budgetMax: 2500,
    comment: '1個164円の大型唐揚げがヤバい。メガジョッキとの組み合わせが最強コスパ。',
    rating: 4,
    googleMapsUrl: 'https://maps.google.com/?q=とりいちず+鶴橋',
    isActive: true,
    createdAt: '2026-03-16',
  },
  {
    id: '4',
    name: '酒場やまと',
    area: 'namba',
    genre: 'izakaya',
    budgetMin: 2000,
    budgetMax: 3500,
    comment: 'なんばの裏路地にある大衆酒場。ホルモン煮込みが絶品。常連のおっちゃんとの会話も楽しい。',
    rating: 4,
    googleMapsUrl: 'https://maps.google.com/?q=酒場やまと+難波',
    isActive: true,
    createdAt: '2026-03-16',
  },
  {
    id: '5',
    name: '串カツ だるま 新世界本店',
    area: 'shinsekai',
    genre: 'kushikatsu',
    budgetMin: 1500,
    budgetMax: 3000,
    comment: '王道中の王道。観光客も多いけど、やっぱりここの串カツは別格。ソース二度づけ禁止！',
    rating: 5,
    googleMapsUrl: 'https://maps.google.com/?q=串カツだるま+新世界',
    isActive: true,
    createdAt: '2026-03-16',
  },
  {
    id: '6',
    name: '手造りうどん 楽々',
    area: 'other',
    genre: 'other',
    budgetMin: 1000,
    budgetMax: 1500,
    comment: '大阪NO.1の呼び声高いうどん屋。黒毛和牛肉ぶっかけは行列に並ぶ価値あり。',
    rating: 5,
    googleMapsUrl: 'https://maps.google.com/?q=手造りうどん楽々+交野市',
    isActive: true,
    createdAt: '2026-03-16',
  },
  {
    id: '7',
    name: 'もつ焼き 稲垣',
    area: 'kyobashi',
    genre: 'yakiniku',
    budgetMin: 2000,
    budgetMax: 3500,
    comment: '京橋のディープゾーンにあるもつ焼き屋。レバーの鮮度がハンパない。赤ワインと合わせるのが通。',
    rating: 4,
    googleMapsUrl: 'https://maps.google.com/?q=もつ焼き稲垣+京橋+大阪',
    isActive: true,
    createdAt: '2026-03-16',
  },
  {
    id: '8',
    name: '天王寺ホルモン',
    area: 'abeno',
    genre: 'yakiniku',
    budgetMin: 1500,
    budgetMax: 2500,
    comment: 'ホルモン一皿300円〜。ビールが進みすぎて危険。一人焼肉デビューにもおすすめ。',
    rating: 3,
    googleMapsUrl: 'https://maps.google.com/?q=天王寺ホルモン',
    isActive: true,
    createdAt: '2026-03-16',
  },
  {
    id: '9',
    name: '寿司と炉端 ぬる燗',
    area: 'umeda',
    genre: 'sushi',
    budgetMin: 3000,
    budgetMax: 5000,
    comment: '梅田で落ち着いて一人飲みするならここ。カウンターで日本酒と握りを。大人の贅沢。',
    rating: 4,
    googleMapsUrl: 'https://maps.google.com/?q=ぬる燗+梅田',
    isActive: true,
    createdAt: '2026-03-16',
  },
  {
    id: '10',
    name: '麺屋 丈六',
    area: 'namba',
    genre: 'ramen',
    budgetMin: 800,
    budgetMax: 1200,
    comment: '難波の名店。醤油ラーメンのキレが半端ない。〆の一杯はここで決まり。',
    rating: 5,
    googleMapsUrl: 'https://maps.google.com/?q=麺屋丈六+難波',
    isActive: true,
    createdAt: '2026-03-16',
  },
];
